//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace WcfTestApplication.devcrmmutuaide {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: L'élément d'extension WSDL facultatif 'PolicyReference' à partir de l'espace de noms 'http://schemas.xmlsoap.org/ws/2004/09/policy' n'est pas géré.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IMutuaideService", Namespace="http://tempuri.org/")]
    public partial class MutuaideService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetEmailByExchangeIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEmailByExchangeIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRequestByPhoneNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback WelcomeCallOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContractByBinOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCustomerBinOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePaymentMethodOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsCustomerActiveOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback MailValidationOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchServicesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MutuaideService() {
            this.Url = global::WcfTestApplication.Properties.Settings.Default.WcfTestApplication_devcrmmutuaide_MutuaideService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetEmailByExchangeIdCompletedEventHandler GetEmailByExchangeIdCompleted;
        
        /// <remarks/>
        public event UpdateEmailByExchangeIdCompletedEventHandler UpdateEmailByExchangeIdCompleted;
        
        /// <remarks/>
        public event GetRequestByPhoneNumberCompletedEventHandler GetRequestByPhoneNumberCompleted;
        
        /// <remarks/>
        public event WelcomeCallCompletedEventHandler WelcomeCallCompleted;
        
        /// <remarks/>
        public event GetContractByBinCompletedEventHandler GetContractByBinCompleted;
        
        /// <remarks/>
        public event UpdateCustomerBinCompletedEventHandler UpdateCustomerBinCompleted;
        
        /// <remarks/>
        public event UpdatePaymentMethodCompletedEventHandler UpdatePaymentMethodCompleted;
        
        /// <remarks/>
        public event RetrieveCustomerCompletedEventHandler RetrieveCustomerCompleted;
        
        /// <remarks/>
        public event IsCustomerActiveCompletedEventHandler IsCustomerActiveCompleted;
        
        /// <remarks/>
        public event GetLastRequestCompletedEventHandler GetLastRequestCompleted;
        
        /// <remarks/>
        public event MailValidationCompletedEventHandler MailValidationCompleted;
        
        /// <remarks/>
        public event SearchServicesCompletedEventHandler SearchServicesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMutuaideService/GetEmailByExchangeId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement GetEmailByExchangeId([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string messageId) {
            object[] results = this.Invoke("GetEmailByExchangeId", new object[] {
                        messageId});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetEmailByExchangeIdAsync(string messageId) {
            this.GetEmailByExchangeIdAsync(messageId, null);
        }
        
        /// <remarks/>
        public void GetEmailByExchangeIdAsync(string messageId, object userState) {
            if ((this.GetEmailByExchangeIdOperationCompleted == null)) {
                this.GetEmailByExchangeIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmailByExchangeIdOperationCompleted);
            }
            this.InvokeAsync("GetEmailByExchangeId", new object[] {
                        messageId}, this.GetEmailByExchangeIdOperationCompleted, userState);
        }
        
        private void OnGetEmailByExchangeIdOperationCompleted(object arg) {
            if ((this.GetEmailByExchangeIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmailByExchangeIdCompleted(this, new GetEmailByExchangeIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMutuaideService/UpdateEmailByExchangeId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement UpdateEmailByExchangeId([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string messageId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string domainName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName) {
            object[] results = this.Invoke("UpdateEmailByExchangeId", new object[] {
                        messageId,
                        domainName,
                        userName});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateEmailByExchangeIdAsync(string messageId, string domainName, string userName) {
            this.UpdateEmailByExchangeIdAsync(messageId, domainName, userName, null);
        }
        
        /// <remarks/>
        public void UpdateEmailByExchangeIdAsync(string messageId, string domainName, string userName, object userState) {
            if ((this.UpdateEmailByExchangeIdOperationCompleted == null)) {
                this.UpdateEmailByExchangeIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEmailByExchangeIdOperationCompleted);
            }
            this.InvokeAsync("UpdateEmailByExchangeId", new object[] {
                        messageId,
                        domainName,
                        userName}, this.UpdateEmailByExchangeIdOperationCompleted, userState);
        }
        
        private void OnUpdateEmailByExchangeIdOperationCompleted(object arg) {
            if ((this.UpdateEmailByExchangeIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEmailByExchangeIdCompleted(this, new UpdateEmailByExchangeIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMutuaideService/GetRequestByPhoneNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement GetRequestByPhoneNumber([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phoneNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string dialNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string phoneCallId) {
            object[] results = this.Invoke("GetRequestByPhoneNumber", new object[] {
                        phoneNumber,
                        dialNumber,
                        phoneCallId});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetRequestByPhoneNumberAsync(string phoneNumber, string dialNumber, string phoneCallId) {
            this.GetRequestByPhoneNumberAsync(phoneNumber, dialNumber, phoneCallId, null);
        }
        
        /// <remarks/>
        public void GetRequestByPhoneNumberAsync(string phoneNumber, string dialNumber, string phoneCallId, object userState) {
            if ((this.GetRequestByPhoneNumberOperationCompleted == null)) {
                this.GetRequestByPhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRequestByPhoneNumberOperationCompleted);
            }
            this.InvokeAsync("GetRequestByPhoneNumber", new object[] {
                        phoneNumber,
                        dialNumber,
                        phoneCallId}, this.GetRequestByPhoneNumberOperationCompleted, userState);
        }
        
        private void OnGetRequestByPhoneNumberOperationCompleted(object arg) {
            if ((this.GetRequestByPhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRequestByPhoneNumberCompleted(this, new GetRequestByPhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMutuaideService/WelcomeCall", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement WelcomeCall([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pcidssId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string callerId) {
            object[] results = this.Invoke("WelcomeCall", new object[] {
                        pcidssId,
                        callerId});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void WelcomeCallAsync(string pcidssId, string callerId) {
            this.WelcomeCallAsync(pcidssId, callerId, null);
        }
        
        /// <remarks/>
        public void WelcomeCallAsync(string pcidssId, string callerId, object userState) {
            if ((this.WelcomeCallOperationCompleted == null)) {
                this.WelcomeCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWelcomeCallOperationCompleted);
            }
            this.InvokeAsync("WelcomeCall", new object[] {
                        pcidssId,
                        callerId}, this.WelcomeCallOperationCompleted, userState);
        }
        
        private void OnWelcomeCallOperationCompleted(object arg) {
            if ((this.WelcomeCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WelcomeCallCompleted(this, new WelcomeCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMutuaideService/GetContractByBin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement GetContractByBin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string binCode) {
            object[] results = this.Invoke("GetContractByBin", new object[] {
                        binCode});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetContractByBinAsync(string binCode) {
            this.GetContractByBinAsync(binCode, null);
        }
        
        /// <remarks/>
        public void GetContractByBinAsync(string binCode, object userState) {
            if ((this.GetContractByBinOperationCompleted == null)) {
                this.GetContractByBinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContractByBinOperationCompleted);
            }
            this.InvokeAsync("GetContractByBin", new object[] {
                        binCode}, this.GetContractByBinOperationCompleted, userState);
        }
        
        private void OnGetContractByBinOperationCompleted(object arg) {
            if ((this.GetContractByBinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContractByBinCompleted(this, new GetContractByBinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMutuaideService/UpdateCustomerBin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement UpdateCustomerBin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pcidssId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string binCode) {
            object[] results = this.Invoke("UpdateCustomerBin", new object[] {
                        pcidssId,
                        binCode});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCustomerBinAsync(string pcidssId, string binCode) {
            this.UpdateCustomerBinAsync(pcidssId, binCode, null);
        }
        
        /// <remarks/>
        public void UpdateCustomerBinAsync(string pcidssId, string binCode, object userState) {
            if ((this.UpdateCustomerBinOperationCompleted == null)) {
                this.UpdateCustomerBinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCustomerBinOperationCompleted);
            }
            this.InvokeAsync("UpdateCustomerBin", new object[] {
                        pcidssId,
                        binCode}, this.UpdateCustomerBinOperationCompleted, userState);
        }
        
        private void OnUpdateCustomerBinOperationCompleted(object arg) {
            if ((this.UpdateCustomerBinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCustomerBinCompleted(this, new UpdateCustomerBinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMutuaideService/UpdatePaymentMethod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement UpdatePaymentMethod([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string demandeId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string paymentId) {
            object[] results = this.Invoke("UpdatePaymentMethod", new object[] {
                        demandeId,
                        paymentId});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePaymentMethodAsync(string demandeId, string paymentId) {
            this.UpdatePaymentMethodAsync(demandeId, paymentId, null);
        }
        
        /// <remarks/>
        public void UpdatePaymentMethodAsync(string demandeId, string paymentId, object userState) {
            if ((this.UpdatePaymentMethodOperationCompleted == null)) {
                this.UpdatePaymentMethodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePaymentMethodOperationCompleted);
            }
            this.InvokeAsync("UpdatePaymentMethod", new object[] {
                        demandeId,
                        paymentId}, this.UpdatePaymentMethodOperationCompleted, userState);
        }
        
        private void OnUpdatePaymentMethodOperationCompleted(object arg) {
            if ((this.UpdatePaymentMethodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePaymentMethodCompleted(this, new UpdatePaymentMethodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMutuaideService/RetrieveCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement RetrieveCustomer([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lastName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string firstName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string birthday) {
            object[] results = this.Invoke("RetrieveCustomer", new object[] {
                        lastName,
                        firstName,
                        birthday});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveCustomerAsync(string lastName, string firstName, string birthday) {
            this.RetrieveCustomerAsync(lastName, firstName, birthday, null);
        }
        
        /// <remarks/>
        public void RetrieveCustomerAsync(string lastName, string firstName, string birthday, object userState) {
            if ((this.RetrieveCustomerOperationCompleted == null)) {
                this.RetrieveCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveCustomerOperationCompleted);
            }
            this.InvokeAsync("RetrieveCustomer", new object[] {
                        lastName,
                        firstName,
                        birthday}, this.RetrieveCustomerOperationCompleted, userState);
        }
        
        private void OnRetrieveCustomerOperationCompleted(object arg) {
            if ((this.RetrieveCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveCustomerCompleted(this, new RetrieveCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMutuaideService/IsCustomerActive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement IsCustomerActive([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pcidssId) {
            object[] results = this.Invoke("IsCustomerActive", new object[] {
                        pcidssId});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void IsCustomerActiveAsync(string pcidssId) {
            this.IsCustomerActiveAsync(pcidssId, null);
        }
        
        /// <remarks/>
        public void IsCustomerActiveAsync(string pcidssId, object userState) {
            if ((this.IsCustomerActiveOperationCompleted == null)) {
                this.IsCustomerActiveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsCustomerActiveOperationCompleted);
            }
            this.InvokeAsync("IsCustomerActive", new object[] {
                        pcidssId}, this.IsCustomerActiveOperationCompleted, userState);
        }
        
        private void OnIsCustomerActiveOperationCompleted(object arg) {
            if ((this.IsCustomerActiveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsCustomerActiveCompleted(this, new IsCustomerActiveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMutuaideService/GetLastRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement GetLastRequest([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pcidssId) {
            object[] results = this.Invoke("GetLastRequest", new object[] {
                        pcidssId});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastRequestAsync(string pcidssId) {
            this.GetLastRequestAsync(pcidssId, null);
        }
        
        /// <remarks/>
        public void GetLastRequestAsync(string pcidssId, object userState) {
            if ((this.GetLastRequestOperationCompleted == null)) {
                this.GetLastRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastRequestOperationCompleted);
            }
            this.InvokeAsync("GetLastRequest", new object[] {
                        pcidssId}, this.GetLastRequestOperationCompleted, userState);
        }
        
        private void OnGetLastRequestOperationCompleted(object arg) {
            if ((this.GetLastRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastRequestCompleted(this, new GetLastRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMutuaideService/MailValidation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MailValidation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, out bool MailValidationResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool MailValidationResultSpecified) {
            object[] results = this.Invoke("MailValidation", new object[] {
                        email});
            MailValidationResult = ((bool)(results[0]));
            MailValidationResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void MailValidationAsync(string email) {
            this.MailValidationAsync(email, null);
        }
        
        /// <remarks/>
        public void MailValidationAsync(string email, object userState) {
            if ((this.MailValidationOperationCompleted == null)) {
                this.MailValidationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMailValidationOperationCompleted);
            }
            this.InvokeAsync("MailValidation", new object[] {
                        email}, this.MailValidationOperationCompleted, userState);
        }
        
        private void OnMailValidationOperationCompleted(object arg) {
            if ((this.MailValidationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MailValidationCompleted(this, new MailValidationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMutuaideService/SearchServices", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public jsonReturn SearchServices([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clientId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string subtypeId) {
            object[] results = this.Invoke("SearchServices", new object[] {
                        clientId,
                        subtypeId});
            return ((jsonReturn)(results[0]));
        }
        
        /// <remarks/>
        public void SearchServicesAsync(string clientId, string subtypeId) {
            this.SearchServicesAsync(clientId, subtypeId, null);
        }
        
        /// <remarks/>
        public void SearchServicesAsync(string clientId, string subtypeId, object userState) {
            if ((this.SearchServicesOperationCompleted == null)) {
                this.SearchServicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchServicesOperationCompleted);
            }
            this.InvokeAsync("SearchServices", new object[] {
                        clientId,
                        subtypeId}, this.SearchServicesOperationCompleted, userState);
        }
        
        private void OnSearchServicesOperationCompleted(object arg) {
            if ((this.SearchServicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchServicesCompleted(this, new SearchServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MutuaideWCF")]
    public partial class jsonReturn {
        
        private CustomReturnCode errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorLabelField;
        
        private ServiceEntity[] servicesField;
        
        /// <remarks/>
        public CustomReturnCode errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorLabel {
            get {
                return this.errorLabelField;
            }
            set {
                this.errorLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ServiceEntity[] services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MutuaideWCF")]
    public enum CustomReturnCode {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        CustomerNotFound,
        
        /// <remarks/>
        ContractNotFound,
        
        /// <remarks/>
        CustomerWithoutContract,
        
        /// <remarks/>
        RequestNotFound,
        
        /// <remarks/>
        RequestFound,
        
        /// <remarks/>
        MailNotFound,
        
        /// <remarks/>
        MailInProgress,
        
        /// <remarks/>
        MailClosed,
        
        /// <remarks/>
        NewRequest,
        
        /// <remarks/>
        MultipleRequest,
        
        /// <remarks/>
        SubTypeNotFound,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MutuaideWCF")]
    public partial class ServiceEntity {
        
        private string new_accountidField;
        
        private string new_accountnameField;
        
        private string new_keywordsField;
        
        private string new_serviceField;
        
        private string new_serviceidField;
        
        private int priorityField;
        
        private bool priorityFieldSpecified;
        
        /// <remarks/>
        public string new_accountid {
            get {
                return this.new_accountidField;
            }
            set {
                this.new_accountidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string new_accountname {
            get {
                return this.new_accountnameField;
            }
            set {
                this.new_accountnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string new_keywords {
            get {
                return this.new_keywordsField;
            }
            set {
                this.new_keywordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string new_service {
            get {
                return this.new_serviceField;
            }
            set {
                this.new_serviceField = value;
            }
        }
        
        /// <remarks/>
        public string new_serviceid {
            get {
                return this.new_serviceidField;
            }
            set {
                this.new_serviceidField = value;
            }
        }
        
        /// <remarks/>
        public int priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetEmailByExchangeIdCompletedEventHandler(object sender, GetEmailByExchangeIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmailByExchangeIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmailByExchangeIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdateEmailByExchangeIdCompletedEventHandler(object sender, UpdateEmailByExchangeIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateEmailByExchangeIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateEmailByExchangeIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetRequestByPhoneNumberCompletedEventHandler(object sender, GetRequestByPhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRequestByPhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRequestByPhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void WelcomeCallCompletedEventHandler(object sender, WelcomeCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WelcomeCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WelcomeCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetContractByBinCompletedEventHandler(object sender, GetContractByBinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContractByBinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContractByBinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdateCustomerBinCompletedEventHandler(object sender, UpdateCustomerBinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCustomerBinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCustomerBinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdatePaymentMethodCompletedEventHandler(object sender, UpdatePaymentMethodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePaymentMethodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePaymentMethodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void RetrieveCustomerCompletedEventHandler(object sender, RetrieveCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void IsCustomerActiveCompletedEventHandler(object sender, IsCustomerActiveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCustomerActiveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsCustomerActiveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetLastRequestCompletedEventHandler(object sender, GetLastRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void MailValidationCompletedEventHandler(object sender, MailValidationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MailValidationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MailValidationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool MailValidationResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool MailValidationResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SearchServicesCompletedEventHandler(object sender, SearchServicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public jsonReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((jsonReturn)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591